# Conexión a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/smart_finance_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate: Crea/Actualiza las tablas automáticamente basándose en tus clases Java
spring.jpa.hibernate.ddl-auto=update

# Muestra en la consola el código SQL que Spring Boot ejecuta por debajo (muy útil para debug)
spring.jpa.show-sql=true