# Conexión a MySQL (asegúrate de crear una base de datos vacía en MySQL llamada 'finanzas_db')
spring.datasource.url=jdbc:mysql://localhost:3306/finanzas_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# La magia que crea las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update

# Para ver en la consola de IntelliJ el SQL que Spring ejecuta por debajo
spring.jpa.show-sql=true